export type Profile = {
  pace: number;        // 0-100: low=slow, high=packed
  environment: number; // 0-100: low=nature, high=urban
  culture: number;     // 0-100: low=surface, high=deep
  adventure: number;   // 0-100: low=relaxed, high=thrill
  food: number;        // 0-100: low=familiar, high=curious
  budget: number;      // 0-100: low=shoestring, high=luxury
  climate: number;     // 0-100: low=cold, high=hot
};

export type Country = {
  code: string;       // ISO alpha-3
  name: string;
  flag: string;
  region: string;
  continent: string;
  profile: Profile;
  description: string;
  why?: string;
  imageUrl: string;
  tags: string[];
  bestMonths: string;
  dailyCost: string;
  visa: string;
  matchScore?: number;
};

export type Archetype = {
  name: string;
  desc: string;
  traits: { icon: string; label: string; color: string }[];
  color: string;
};

export const ARCHETYPES: Record<string, Archetype> = {
  "Slow Wanderer": {
    name: "Slow Wanderer",
    desc: "You travel to settle in, not check off. A neighborhood café, a long conversation, an afternoon without plans — that's the good stuff. You find depth in fewer places.",
    traits: [
      { icon: "📖", label: "Culture seeker", color: "#9B6FD4" },
      { icon: "☕", label: "Slow traveler", color: "#1D9E75" },
      { icon: "🍜", label: "Food curious", color: "#F0997B" },
      { icon: "🗺️", label: "Off the beaten path", color: "#4A9EBD" },
    ],
    color: "#1D9E75",
  },
  "City Nomad": {
    name: "City Nomad",
    desc: "You're drawn to the pulse of a city — its design, its food scene, its people. You can navigate a metro system in 20 minutes and always find the best local spot.",
    traits: [
      { icon: "🏙️", label: "Urban explorer", color: "#4A9EBD" },
      { icon: "🍽️", label: "Restaurant hunter", color: "#F0997B" },
      { icon: "🎭", label: "Culture junkie", color: "#9B6FD4" },
      { icon: "⚡", label: "Fast adapter", color: "#F5B942" },
    ],
    color: "#4A9EBD",
  },
  "Culture Hunter": {
    name: "Culture Hunter",
    desc: "Museums, ruins, local markets, hidden temples — you travel to understand. History isn't a backdrop; it's the whole point. You always leave knowing more than you arrived.",
    traits: [
      { icon: "🏛️", label: "History buff", color: "#9B6FD4" },
      { icon: "🎨", label: "Art & design lover", color: "#E85D75" },
      { icon: "📚", label: "Deep diver", color: "#1D9E75" },
      { icon: "🧭", label: "Intentional explorer", color: "#4A9EBD" },
    ],
    color: "#9B6FD4",
  },
  "Backpacker Spirit": {
    name: "Backpacker Spirit",
    desc: "You travel light and live fully. Spontaneous detours, budget guesthouses with great stories, and the next country always calling. The journey is the destination.",
    traits: [
      { icon: "🎒", label: "Light packer", color: "#F5B942" },
      { icon: "🌄", label: "Adventure seeker", color: "#F0997B" },
      { icon: "🤝", label: "Social traveler", color: "#1D9E75" },
      { icon: "🔀", label: "Spontaneous", color: "#E85D75" },
    ],
    color: "#F0997B",
  },
};

export const DIMENSIONS: { key: keyof Profile; name: string; left: string; right: string; color: string }[] = [
  { key: "pace",        name: "Pace",         left: "Slow",     right: "Packed",  color: "#1D9E75" },
  { key: "environment", name: "Setting",      left: "Nature",   right: "Urban",   color: "#4A9EBD" },
  { key: "culture",     name: "Culture",      left: "Surface",  right: "Deep",    color: "#9B6FD4" },
  { key: "adventure",   name: "Adventure",    left: "Relaxed",  right: "Thrill",  color: "#F0997B" },
  { key: "food",        name: "Food",         left: "Familiar", right: "Curious", color: "#E85D75" },
  { key: "budget",      name: "Budget",       left: "Stretch",  right: "Splurge", color: "#F5B942" },
  { key: "climate",     name: "Climate",      left: "Cool",     right: "Warm",    color: "#5BA85A" },
];

export const QUESTIONS = [
  {
    q: "How do you feel about not having a plan?",
    opts: [
      "Love it — total freedom",
      "Fine if there's a rough outline",
      "Prefer a solid itinerary",
      "Need every hour mapped out",
    ],
  },
  {
    q: "Your ideal travel group is:",
    opts: [
      "Solo, always",
      "Partner or close friend",
      "Small group (3–5)",
      "Big crew, more the merrier",
    ],
  },
  {
    q: 'Your dream "perfect day" looks like:',
    opts: [
      "Hammock, book, one great meal",
      "Museum → café → sunset walk",
      "Dawn hike, three neighborhoods",
      "Beach morning, city night",
    ],
  },
  {
    q: "Language barriers are:",
    opts: [
      "Part of the adventure",
      "Fine — I'll figure it out",
      "A bit stressful",
      "A dealbreaker",
    ],
  },
  {
    q: "Your budget philosophy:",
    opts: [
      "Stretch every dollar",
      "Comfort matters, mid-range",
      "Splurge where it counts",
      "Only the best, always",
    ],
  },
  {
    q: "Food adventures — you're:",
    opts: [
      "All in — street food, weird stuff",
      "Curious but with limits",
      "Stick to familiar cuisines",
      "Safe choices only",
    ],
  },
  {
    q: "Dream climate:",
    opts: [
      "Cool and dramatic — mountains, fog",
      "Warm and dry — Mediterranean",
      "Hot and lush — tropical",
      "Cold and crisp — Nordic",
    ],
  },
  {
    q: "Your ideal trip length:",
    opts: [
      "Weekend escape (2–4 days)",
      "One to two weeks",
      "A full month",
      "Open-ended, no return ticket",
    ],
  },
];

// Scores each answer contributes to profile dimensions (0–100)
export const ANSWER_SCORES: Record<number, Record<number, Partial<Profile>>> = {
  0: {
    0: { adventure: 90, pace: 35 },
    1: { adventure: 65, pace: 50 },
    2: { adventure: 35, pace: 65 },
    3: { adventure: 15, pace: 85 },
  },
  1: {
    0: { environment: 25 },
    1: { environment: 45 },
    2: { environment: 60, pace: 55 },
    3: { environment: 78, pace: 70 },
  },
  2: {
    0: { pace: 20, adventure: 20 },
    1: { pace: 50, culture: 78 },
    2: { pace: 85, adventure: 75 },
    3: { pace: 65, environment: 60 },
  },
  3: {
    0: { adventure: 85, culture: 82 },
    1: { adventure: 65, culture: 65 },
    2: { adventure: 38, culture: 45 },
    3: { adventure: 12, culture: 20 },
  },
  4: {
    0: { budget: 12 },
    1: { budget: 48 },
    2: { budget: 72 },
    3: { budget: 95 },
  },
  5: {
    0: { food: 95 },
    1: { food: 70 },
    2: { food: 38 },
    3: { food: 12 },
  },
  6: {
    0: { climate: 15 },
    1: { climate: 55 },
    2: { climate: 88 },
    3: { climate: 5 },
  },
  7: {
    0: { pace: 78 },
    1: { pace: 55 },
    2: { pace: 38 },
    3: { pace: 28, adventure: 82, budget: 18 },
  },
};

export const COUNTRIES: Country[] = [
  {
    code: "PRT",
    name: "Portugal",
    flag: "🇵🇹",
    region: "Southern Europe",
    continent: "europe",
    profile: { pace: 35, environment: 52, culture: 78, adventure: 42, food: 72, budget: 48, climate: 65 },
    description: "Easygoing pace, deep culture, food that rewards curiosity, and a mid-range budget — Portugal is one of Europe's most underrated destinations.",
    why: "Easygoing pace, deep culture, food that rewards curiosity, and mid-range budget — all dialed to your profile.",
    imageUrl: "https://images.unsplash.com/photo-1513735492246-483525079686?w=800&auto=format&fit=crop&q=80",
    tags: ["europe", "food", "culture", "history"],
    bestMonths: "Apr – Jun, Sep – Oct",
    dailyCost: "$60–100",
    visa: "Visa-free (EU/US/UK)",
  },
  {
    code: "JPN",
    name: "Japan",
    flag: "🇯🇵",
    region: "East Asia",
    continent: "asia",
    profile: { pace: 68, environment: 72, culture: 92, adventure: 52, food: 88, budget: 62, climate: 52 },
    description: "Hyper-organized yet endlessly surprising. Japan rewards both the planner and the wanderer — with some of the world's best food in between.",
    why: "Hyper-organized yet endlessly surprising. Perfect for the planner who still wants to be wowed at every turn.",
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&auto=format&fit=crop&q=80",
    tags: ["asia", "food", "culture", "temples"],
    bestMonths: "Mar – May, Oct – Nov",
    dailyCost: "$80–150",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "COL",
    name: "Colombia",
    flag: "🇨🇴",
    region: "South America",
    continent: "americas",
    profile: { pace: 72, environment: 55, culture: 68, adventure: 78, food: 78, budget: 32, climate: 78 },
    description: "Biodiversity, city culture, and some of the world's warmest locals. A high-energy match for curious spirits on a budget.",
    why: "Biodiversity, city culture, and some of the world's warmest locals. A high-energy match for curious spirits.",
    imageUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&auto=format&fit=crop&q=80",
    tags: ["americas", "adventure", "nature", "city"],
    bestMonths: "Dec – Mar",
    dailyCost: "$35–70",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "MAR",
    name: "Morocco",
    flag: "🇲🇦",
    region: "North Africa",
    continent: "africa",
    profile: { pace: 62, environment: 42, culture: 88, adventure: 72, food: 82, budget: 28, climate: 72 },
    description: "Sensory overload in the best way. Medinas, mountains, and Sahara — all within reach of each other.",
    why: "Sensory overload in the best way. Medinas, mountains, and sahara — all within reach of each other.",
    imageUrl: "https://images.unsplash.com/photo-1539635278303-d4002c07eae3?w=800&auto=format&fit=crop&q=80",
    tags: ["africa", "culture", "desert", "food"],
    bestMonths: "Mar – May, Sep – Nov",
    dailyCost: "$30–65",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "ISL",
    name: "Iceland",
    flag: "🇮🇸",
    region: "Northern Europe",
    continent: "europe",
    profile: { pace: 55, environment: 18, culture: 58, adventure: 82, food: 52, budget: 72, climate: 12 },
    description: "Otherworldly landscapes and zero crowds off-season. For the traveler who doesn't need warm to feel alive.",
    why: "Otherworldly landscapes and zero crowds off-season. For the traveler who doesn't need warm to feel alive.",
    imageUrl: "https://images.unsplash.com/photo-1476610182048-b716b8518aae?w=800&auto=format&fit=crop&q=80",
    tags: ["europe", "nature", "adventure", "landscape"],
    bestMonths: "Jun – Aug, Dec – Feb",
    dailyCost: "$120–200",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "VNM",
    name: "Vietnam",
    flag: "🇻🇳",
    region: "Southeast Asia",
    continent: "asia",
    profile: { pace: 62, environment: 38, culture: 72, adventure: 65, food: 92, budget: 18, climate: 80 },
    description: "Street food capital of the world, ancient towns, and a coastline that won't quit. All on a shoestring.",
    why: "Street food capital of the world, ancient towns, and a coastline that won't quit.",
    imageUrl: "https://images.unsplash.com/photo-1557750255-c76072a7aad1?w=800&auto=format&fit=crop&q=80",
    tags: ["asia", "food", "coast", "budget"],
    bestMonths: "Nov – Apr",
    dailyCost: "$25–55",
    visa: "30-day e-visa",
  },
  {
    code: "MEX",
    name: "Mexico",
    flag: "🇲🇽",
    region: "North America",
    continent: "americas",
    profile: { pace: 58, environment: 50, culture: 82, adventure: 65, food: 88, budget: 32, climate: 75 },
    description: "Ancient ruins, coast, and a food culture that punches far above its weight class.",
    why: "Ancient ruins, coast, and a food culture that punches far above its weight class.",
    imageUrl: "https://images.unsplash.com/photo-1518638150340-f706e86654de?w=800&auto=format&fit=crop&q=80",
    tags: ["americas", "food", "culture", "ruins"],
    bestMonths: "Nov – Apr",
    dailyCost: "$35–75",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "GEO",
    name: "Georgia",
    flag: "🇬🇪",
    region: "Caucasus",
    continent: "europe",
    profile: { pace: 42, environment: 32, culture: 82, adventure: 70, food: 78, budget: 22, climate: 52 },
    description: "Underrated gem: ancient wine culture, mountain villages, Tbilisi's buzzing art scene — all for next to nothing.",
    why: "Underrated gem: ancient wine culture, mountain villages, Tbilisi's buzzing art scene.",
    imageUrl: "https://images.unsplash.com/photo-1590073844006-33379778ae09?w=800&auto=format&fit=crop&q=80",
    tags: ["europe", "culture", "wine", "mountains"],
    bestMonths: "May – Jun, Sep – Oct",
    dailyCost: "$25–55",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "THA",
    name: "Thailand",
    flag: "🇹🇭",
    region: "Southeast Asia",
    continent: "asia",
    profile: { pace: 55, environment: 45, culture: 75, adventure: 60, food: 88, budget: 25, climate: 88 },
    description: "Temple culture, street food markets, and warm waters — endlessly accessible and deeply rewarding.",
    why: "Temple culture, street food markets, and warm waters — endlessly accessible and deeply rewarding.",
    imageUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&auto=format&fit=crop&q=80",
    tags: ["asia", "food", "temples", "beach"],
    bestMonths: "Nov – Mar",
    dailyCost: "$30–70",
    visa: "30-day on arrival",
  },
  {
    code: "PER",
    name: "Peru",
    flag: "🇵🇪",
    region: "South America",
    continent: "americas",
    profile: { pace: 65, environment: 22, culture: 88, adventure: 82, food: 72, budget: 28, climate: 45 },
    description: "Ancient civilizations, extreme landscapes, and cuisine that's having a global moment. Machu Picchu is just the start.",
    why: "Ancient civilizations, extreme landscapes, and cuisine that's having a global moment.",
    imageUrl: "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&auto=format&fit=crop&q=80",
    tags: ["americas", "history", "adventure", "nature"],
    bestMonths: "May – Sep",
    dailyCost: "$35–70",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "ITA",
    name: "Italy",
    flag: "🇮🇹",
    region: "Southern Europe",
    continent: "europe",
    profile: { pace: 50, environment: 58, culture: 92, adventure: 40, food: 92, budget: 58, climate: 65 },
    description: "The benchmark for culture, food, and beauty. Italy is endlessly rewarding whether it's your first visit or your tenth.",
    why: "The benchmark for culture, food, and beauty — a destination that rewards every type of traveler.",
    imageUrl: "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=800&auto=format&fit=crop&q=80",
    tags: ["europe", "food", "culture", "history"],
    bestMonths: "Apr – Jun, Sep – Oct",
    dailyCost: "$80–150",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "ESP",
    name: "Spain",
    flag: "🇪🇸",
    region: "Southern Europe",
    continent: "europe",
    profile: { pace: 55, environment: 58, culture: 82, adventure: 52, food: 88, budget: 52, climate: 72 },
    description: "Architecture, tapas culture, and a nightlife that starts at midnight. Spain runs on its own clock.",
    why: "Architecture, tapas culture, and a nightlife that starts at midnight — Spain on your terms.",
    imageUrl: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&auto=format&fit=crop&q=80",
    tags: ["europe", "food", "culture", "city"],
    bestMonths: "Apr – Jun, Sep – Oct",
    dailyCost: "$65–120",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "NZL",
    name: "New Zealand",
    flag: "🇳🇿",
    region: "Oceania",
    continent: "oceania",
    profile: { pace: 65, environment: 12, culture: 55, adventure: 92, food: 58, budget: 68, climate: 52 },
    description: "Adventure capital of the world. Every landscape you've ever imagined — fjords, glaciers, beaches — within a few hours' drive.",
    why: "Adventure capital of the world. Every landscape you've imagined is within a few hours' drive.",
    imageUrl: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800&auto=format&fit=crop&q=80",
    tags: ["oceania", "adventure", "nature", "landscape"],
    bestMonths: "Dec – Mar",
    dailyCost: "$80–150",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "IND",
    name: "India",
    flag: "🇮🇳",
    region: "South Asia",
    continent: "asia",
    profile: { pace: 78, environment: 55, culture: 96, adventure: 78, food: 82, budget: 18, climate: 75 },
    description: "The most sensory destination on earth. India is chaotic, spiritual, overwhelming, and unforgettable in equal measure.",
    why: "The most sensory destination on earth — chaotic, spiritual, overwhelming, and unforgettable.",
    imageUrl: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&auto=format&fit=crop&q=80",
    tags: ["asia", "culture", "temples", "food"],
    bestMonths: "Oct – Mar",
    dailyCost: "$20–60",
    visa: "e-Visa required",
  },
  {
    code: "ARG",
    name: "Argentina",
    flag: "🇦🇷",
    region: "South America",
    continent: "americas",
    profile: { pace: 55, environment: 38, culture: 78, adventure: 72, food: 72, budget: 28, climate: 48 },
    description: "Buenos Aires is the Paris of South America. Patagonia is unlike anywhere on earth. Argentina contains multitudes.",
    why: "Buenos Aires, Patagonia, Mendoza wine country — Argentina contains multitudes.",
    imageUrl: "https://images.unsplash.com/photo-1551524559-8af4e6624178?w=800&auto=format&fit=crop&q=80",
    tags: ["americas", "nature", "culture", "city"],
    bestMonths: "Nov – Mar",
    dailyCost: "$30–70",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "GRC",
    name: "Greece",
    flag: "🇬🇷",
    region: "Southern Europe",
    continent: "europe",
    profile: { pace: 38, environment: 45, culture: 85, adventure: 50, food: 80, budget: 52, climate: 72 },
    description: "Ancient ruins, crystal-clear Aegean waters, and tavernas that make you never want to leave. The birthplace of Western civilization is still one of its best destinations.",
    why: "Ancient history, island-hopping, and Mediterranean food culture at a pace that invites lingering.",
    imageUrl: "https://picsum.photos/seed/greece/800/500",
    tags: ["europe", "history", "coast", "food"],
    bestMonths: "Apr – Jun, Sep – Oct",
    dailyCost: "$60–110",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "TUR",
    name: "Turkey",
    flag: "🇹🇷",
    region: "Western Asia",
    continent: "asia",
    profile: { pace: 62, environment: 52, culture: 90, adventure: 62, food: 85, budget: 30, climate: 65 },
    description: "Where Europe meets Asia — Ottoman palaces, Cappadocia's surreal valleys, and food that demands your full attention.",
    why: "Crossroads of civilizations, remarkable food, and affordable luxury that outpunches its price tag.",
    imageUrl: "https://picsum.photos/seed/turkey/800/500",
    tags: ["asia", "culture", "food", "history"],
    bestMonths: "Apr – Jun, Sep – Oct",
    dailyCost: "$35–75",
    visa: "e-Visa required",
  },
  {
    code: "HRV",
    name: "Croatia",
    flag: "🇭🇷",
    region: "Southern Europe",
    continent: "europe",
    profile: { pace: 38, environment: 35, culture: 72, adventure: 55, food: 65, budget: 55, climate: 68 },
    description: "Adriatic islands, Game of Thrones backdrops, and Roman ruins that still feel alive. Croatia balances history with coastline effortlessly.",
    why: "Adriatic blues, old walled cities, and island-hopping at a relaxed European pace.",
    imageUrl: "https://picsum.photos/seed/croatia/800/500",
    tags: ["europe", "coast", "history", "islands"],
    bestMonths: "May – Jun, Sep",
    dailyCost: "$60–110",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "IDN",
    name: "Indonesia",
    flag: "🇮🇩",
    region: "Southeast Asia",
    continent: "asia",
    profile: { pace: 38, environment: 22, culture: 80, adventure: 72, food: 78, budget: 22, climate: 88 },
    description: "Bali's spiritual temples and rice terraces, Lombok's wild beaches, Komodo's dragons — 17,000 islands, infinite possibilities.",
    why: "Spiritual depth, lush landscapes, and world-class surf culture for a fraction of European prices.",
    imageUrl: "https://picsum.photos/seed/indonesia/800/500",
    tags: ["asia", "spiritual", "nature", "beach"],
    bestMonths: "May – Sep",
    dailyCost: "$30–65",
    visa: "30-day on arrival",
  },
  {
    code: "KEN",
    name: "Kenya",
    flag: "🇰🇪",
    region: "East Africa",
    continent: "africa",
    profile: { pace: 52, environment: 8, culture: 70, adventure: 88, food: 55, budget: 48, climate: 72 },
    description: "The Maasai Mara's great migration, Amboseli's Kilimanjaro backdrop, Nairobi's surprising art scene — Kenya is where wildlife becomes personal.",
    why: "Safari at its finest — horizon-to-horizon wildlife, open savannas, and big African skies.",
    imageUrl: "https://picsum.photos/seed/kenya/800/500",
    tags: ["africa", "safari", "wildlife", "nature"],
    bestMonths: "Jul – Sep, Jan – Feb",
    dailyCost: "$60–150",
    visa: "e-Visa required",
  },
  {
    code: "NPL",
    name: "Nepal",
    flag: "🇳🇵",
    region: "South Asia",
    continent: "asia",
    profile: { pace: 55, environment: 5, culture: 82, adventure: 92, food: 52, budget: 20, climate: 30 },
    description: "Home to eight of the world's ten tallest peaks and a culture built around them. Nepal is the ultimate destination for those who want to earn their views.",
    why: "The Himalayas, Buddhist monasteries, and trekking routes that change your perspective — literally.",
    imageUrl: "https://picsum.photos/seed/nepal/800/500",
    tags: ["asia", "mountains", "trekking", "spiritual"],
    bestMonths: "Oct – Nov, Mar – Apr",
    dailyCost: "$25–60",
    visa: "Visa on arrival",
  },
  {
    code: "CRI",
    name: "Costa Rica",
    flag: "🇨🇷",
    region: "Central America",
    continent: "americas",
    profile: { pace: 45, environment: 10, culture: 55, adventure: 85, food: 60, budget: 42, climate: 85 },
    description: "Pura vida — cloud forests, active volcanoes, whitewater rivers, and wildlife around every corner. Costa Rica invented eco-adventure.",
    why: "Biodiversity hotspot with world-class zip-lining, wildlife watching, and beach culture in one compact country.",
    imageUrl: "https://picsum.photos/seed/costarica/800/500",
    tags: ["americas", "nature", "adventure", "wildlife"],
    bestMonths: "Dec – Apr",
    dailyCost: "$55–100",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "JOR",
    name: "Jordan",
    flag: "🇯🇴",
    region: "Middle East",
    continent: "asia",
    profile: { pace: 48, environment: 22, culture: 88, adventure: 68, food: 72, budget: 45, climate: 68 },
    description: "Petra carved from rose-red stone, Wadi Rum's Mars-like desert, and the Dead Sea. Jordan packs ancient wonders into a surprisingly welcoming, safe country.",
    why: "Petra, Wadi Rum, and the Dead Sea — ancient wonders in one of the Middle East's most welcoming countries.",
    imageUrl: "https://picsum.photos/seed/jordan/800/500",
    tags: ["asia", "history", "desert", "culture"],
    bestMonths: "Mar – May, Sep – Nov",
    dailyCost: "$50–90",
    visa: "Visa on arrival",
  },
  {
    code: "CZE",
    name: "Czech Republic",
    flag: "🇨🇿",
    region: "Central Europe",
    continent: "europe",
    profile: { pace: 42, environment: 65, culture: 85, adventure: 38, food: 62, budget: 42, climate: 38 },
    description: "Prague's fairy-tale architecture, world-class beer culture, and medieval town squares that survived the 20th century largely intact.",
    why: "One of Europe's most beautiful medieval capitals — history, architecture, and pub culture at their best.",
    imageUrl: "https://picsum.photos/seed/czechrepublic/800/500",
    tags: ["europe", "history", "culture", "city"],
    bestMonths: "Apr – Jun, Sep – Oct",
    dailyCost: "$50–90",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "KOR",
    name: "South Korea",
    flag: "🇰🇷",
    region: "East Asia",
    continent: "asia",
    profile: { pace: 72, environment: 65, culture: 85, adventure: 55, food: 90, budget: 58, climate: 48 },
    description: "Cutting-edge Seoul alongside ancient palaces, hiking trails minutes from the city, and a food culture that doesn't stop. K-everything is a lifestyle here.",
    why: "Ultra-modern meets deep tradition — and the food scene alone is worth the flight.",
    imageUrl: "https://picsum.photos/seed/southkorea/800/500",
    tags: ["asia", "food", "culture", "city"],
    bestMonths: "Apr – Jun, Sep – Nov",
    dailyCost: "$60–110",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "NOR",
    name: "Norway",
    flag: "🇳🇴",
    region: "Northern Europe",
    continent: "europe",
    profile: { pace: 45, environment: 5, culture: 58, adventure: 80, food: 52, budget: 88, climate: 12 },
    description: "Fjords that make you question if they're real, Northern Lights in winter, and a philosophy of outdoor life that's contagious. Norway is expensive — every cent is worth it.",
    why: "Fjords, Northern Lights, and outdoor culture at its most extreme — expensive but completely unforgettable.",
    imageUrl: "https://picsum.photos/seed/norway/800/500",
    tags: ["europe", "nature", "adventure", "landscape"],
    bestMonths: "Jun – Aug, Dec – Jan",
    dailyCost: "$130–220",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "LKA",
    name: "Sri Lanka",
    flag: "🇱🇰",
    region: "South Asia",
    continent: "asia",
    profile: { pace: 48, environment: 20, culture: 80, adventure: 68, food: 78, budget: 25, climate: 82 },
    description: "Ancient temples, leopard safaris, tea-covered highlands, and Indian Ocean beaches — Sri Lanka is astonishingly diverse for its size.",
    why: "Ancient temples, wildlife safaris, tea highlands, and beaches — four countries' worth of experience in one island.",
    imageUrl: "https://picsum.photos/seed/srilanka/800/500",
    tags: ["asia", "culture", "nature", "beach"],
    bestMonths: "Dec – Mar",
    dailyCost: "$30–65",
    visa: "e-Visa required",
  },
  {
    code: "ECU",
    name: "Ecuador",
    flag: "🇪🇨",
    region: "South America",
    continent: "americas",
    profile: { pace: 55, environment: 8, culture: 65, adventure: 88, food: 62, budget: 28, climate: 65 },
    description: "The Galapagos, the Amazon, and the Andes — three of the world's most extraordinary ecosystems, all within one small country straddling the equator.",
    why: "Galapagos wildlife, Amazon jungle, and Andean highlands all in one small, underrated country.",
    imageUrl: "https://picsum.photos/seed/ecuador/800/500",
    tags: ["americas", "wildlife", "nature", "adventure"],
    bestMonths: "Jun – Sep",
    dailyCost: "$35–75",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "LAO",
    name: "Laos",
    flag: "🇱🇦",
    region: "Southeast Asia",
    continent: "asia",
    profile: { pace: 22, environment: 22, culture: 78, adventure: 60, food: 70, budget: 18, climate: 78 },
    description: "Southeast Asia's best-kept secret. Slow river life, golden temples, and a pace that makes everywhere else feel rushed.",
    why: "The unhurried antidote to over-tourism — river towns, Buddhist culture, and genuinely slow travel.",
    imageUrl: "https://picsum.photos/seed/laos/800/500",
    tags: ["asia", "culture", "temples", "budget"],
    bestMonths: "Nov – Feb",
    dailyCost: "$20–45",
    visa: "Visa on arrival",
  },
  {
    code: "ALB",
    name: "Albania",
    flag: "🇦🇱",
    region: "Southern Europe",
    continent: "europe",
    profile: { pace: 38, environment: 28, culture: 72, adventure: 65, food: 65, budget: 18, climate: 62 },
    description: "Undiscovered Europe. Albanian Riviera beaches rivaling Greece, Ottoman old towns, rugged mountains, and prices from a decade ago.",
    why: "Europe's best-kept secret — Riviera beaches, Ottoman architecture, and some of the continent's lowest prices.",
    imageUrl: "https://picsum.photos/seed/albania/800/500",
    tags: ["europe", "coast", "culture", "budget"],
    bestMonths: "Jun – Sep",
    dailyCost: "$25–55",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "OMN",
    name: "Oman",
    flag: "🇴🇲",
    region: "Middle East",
    continent: "asia",
    profile: { pace: 42, environment: 18, culture: 80, adventure: 72, food: 65, budget: 48, climate: 72 },
    description: "Arabia without the chaos. Ancient forts, dramatic desert wadis, and a warmth of welcome that surprises every first-timer.",
    why: "Desert dunes, ancient forts, and extraordinary hospitality in one of the Middle East's safest destinations.",
    imageUrl: "https://picsum.photos/seed/oman/800/500",
    tags: ["asia", "desert", "culture", "adventure"],
    bestMonths: "Oct – Apr",
    dailyCost: "$55–100",
    visa: "Visa on arrival",
  },
  {
    code: "UZB",
    name: "Uzbekistan",
    flag: "🇺🇿",
    region: "Central Asia",
    continent: "asia",
    profile: { pace: 52, environment: 32, culture: 92, adventure: 62, food: 68, budget: 22, climate: 55 },
    description: "Samarkand's turquoise domes, Bukhara's ancient madrasas, Khiva's walled city — the Silk Road is real and it's still standing.",
    why: "Islamic architecture at its most breathtaking and Silk Road history still visible in the streets.",
    imageUrl: "https://picsum.photos/seed/uzbekistan/800/500",
    tags: ["asia", "history", "culture", "architecture"],
    bestMonths: "Apr – May, Sep – Oct",
    dailyCost: "$30–60",
    visa: "e-Visa required",
  },
  {
    code: "BOL",
    name: "Bolivia",
    flag: "🇧🇴",
    region: "South America",
    continent: "americas",
    profile: { pace: 58, environment: 10, culture: 78, adventure: 85, food: 55, budget: 20, climate: 45 },
    description: "Salar de Uyuni's infinite salt flats, the Amazon basin, colonial Sucre, and an Andean culture that feels untouched. South America's most extreme country.",
    why: "The most dramatic landscapes in South America — from salt flats to jungle — at South America's lowest prices.",
    imageUrl: "https://picsum.photos/seed/bolivia/800/500",
    tags: ["americas", "nature", "adventure", "culture"],
    bestMonths: "May – Oct",
    dailyCost: "$25–55",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "PHL",
    name: "Philippines",
    flag: "🇵🇭",
    region: "Southeast Asia",
    continent: "asia",
    profile: { pace: 48, environment: 18, culture: 65, adventure: 72, food: 72, budget: 22, climate: 85 },
    description: "7,641 islands of turquoise water, powdery beaches, and some of the world's best diving — all delivered with genuine Filipino warmth.",
    why: "Island-hopping paradise with world-class diving, warm people, and beachside life at budget prices.",
    imageUrl: "https://picsum.photos/seed/philippines/800/500",
    tags: ["asia", "islands", "beach", "diving"],
    bestMonths: "Nov – May",
    dailyCost: "$30–65",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "SGP",
    name: "Singapore",
    flag: "🇸🇬",
    region: "Southeast Asia",
    continent: "asia",
    profile: { pace: 78, environment: 88, culture: 78, adventure: 38, food: 92, budget: 80, climate: 88 },
    description: "The city-state that took food seriously enough to give hawker centers a Michelin star. A flawless fusion of Chinese, Malay, and Indian cultures in one immaculate, efficient package.",
    why: "The world's most exciting food city — hawker stalls to fine dining — wrapped in effortless urban infrastructure.",
    imageUrl: "https://picsum.photos/seed/singapore/800/500",
    tags: ["asia", "food", "city", "culture"],
    bestMonths: "Feb – Apr, Aug – Sep",
    dailyCost: "$100–200",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "CHL",
    name: "Chile",
    flag: "🇨🇱",
    region: "South America",
    continent: "americas",
    profile: { pace: 52, environment: 10, culture: 65, adventure: 85, food: 62, budget: 48, climate: 32 },
    description: "From the Atacama's lunar desert to Patagonia's ice fields, Chile is nature at its most theatrical — and wine country in between.",
    why: "Patagonia, Atacama, and wine country — Chile is nature at its most theatrical across every climate zone.",
    imageUrl: "https://picsum.photos/seed/chile/800/500",
    tags: ["americas", "nature", "adventure", "landscape"],
    bestMonths: "Nov – Mar",
    dailyCost: "$50–100",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "BRA",
    name: "Brazil",
    flag: "🇧🇷",
    region: "South America",
    continent: "americas",
    profile: { pace: 65, environment: 28, culture: 80, adventure: 78, food: 78, budget: 38, climate: 82 },
    description: "Amazon rainforest, Iguazu Falls, Carnival, Ipanema, Pantanal wildlife — Brazil operates at a scale that defies comprehension.",
    why: "Amazon, Iguazu, Carnival, and Copacabana — Brazil is epic at every single scale.",
    imageUrl: "https://picsum.photos/seed/brazil/800/500",
    tags: ["americas", "nature", "culture", "adventure"],
    bestMonths: "Dec – Mar",
    dailyCost: "$40–85",
    visa: "Visa-free (US/UK/EU)",
  },
  {
    code: "AUS",
    name: "Australia",
    flag: "🇦🇺",
    region: "Oceania",
    continent: "oceania",
    profile: { pace: 58, environment: 15, culture: 60, adventure: 78, food: 68, budget: 72, climate: 68 },
    description: "Great Barrier Reef, the Outback, world-class coastal cities, and a relaxed culture that makes every visit feel like an extended holiday.",
    why: "Reef, outback, and cities that feel like they were designed for the good life — Australia delivers at every level.",
    imageUrl: "https://picsum.photos/seed/australia/800/500",
    tags: ["oceania", "nature", "adventure", "city"],
    bestMonths: "Sep – Nov, Mar – May",
    dailyCost: "$100–180",
    visa: "ETA required",
  },
  {
    code: "GHA",
    name: "Ghana",
    flag: "🇬🇭",
    region: "West Africa",
    continent: "africa",
    profile: { pace: 55, environment: 42, culture: 85, adventure: 62, food: 72, budget: 28, climate: 82 },
    description: "West Africa's most welcoming gateway — vibrant music scene, powerful colonial history, Cape Coast slave forts, and Accra's rapid-fire energy.",
    why: "West Africa's most accessible destination — music, history, and genuine warmth in equal measure.",
    imageUrl: "https://picsum.photos/seed/ghana/800/500",
    tags: ["africa", "culture", "history", "music"],
    bestMonths: "Nov – Mar",
    dailyCost: "$30–70",
    visa: "Visa-free (US) / e-Visa",
  },
  {
    code: "CUB",
    name: "Cuba",
    flag: "🇨🇺",
    region: "Caribbean",
    continent: "americas",
    profile: { pace: 32, environment: 52, culture: 88, adventure: 48, food: 55, budget: 32, climate: 82 },
    description: "Classic cars, crumbling Havana mansions, live salsa spilling from every doorway — Cuba is a living time capsule that demands you slow all the way down.",
    why: "A living time capsule — Havana's architecture, salsa culture, and sunsets that feel unhurried by design.",
    imageUrl: "https://picsum.photos/seed/cuba/800/500",
    tags: ["americas", "culture", "music", "beach"],
    bestMonths: "Dec – Apr",
    dailyCost: "$35–75",
    visa: "Tourist card required",
  },
];
